source 'https://github.com/CocoaPods/Specs.git'
platform :ios, :deployment_target => '7.0'

pod 'Facebook-iOS-SDK'
pod 'SVProgressHUD'
pod 'PBJVision', :git => 'git@github.com:Maciej-Matuszewski/PBJVision.git'
pod 'TTTAttributedLabel'
pod 'JSQMessagesViewController'
pod 'AMPopTip'
pod 'QBPopupMenu'
pod 'RNGridMenu'
pod 'Parse'
pod 'DBPrivacyHelper'
pod 'CWPopup'
pod 'ChameleonFramework'
pod 'SDWebImage'
pod 'CRGradientNavigationBar'
pod 'EXPhotoViewer'